name: debug_dot
description: A Flutter package that provides a floating debug dot for easy access to development tools and debug options during app development.
version: 0.1.0
repository: https://github.com/malt03/debug_dot
issue_tracker: https://github.com/malt03/debug_dot/issues

topics:
  - debug
  - development
  - tools
  - flutter

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
